FE:
  - head-branch: ["^fe/"]

BE:
  - head-branch: ["^be/"]

APP:
  - head-branch: ["^app/"]

":sparkles: feature":
  - head-branch: ["^(fe|be|app|common)/feat/"]

"🐛 fix":
  - head-branch: ["^(fe|be|app|common)/fix/"]

"📄 documentation":
  - head-branch: ["^(fe|be|app|common)/docs/"]

":art: style":
  - head-branch: ["^(fe|be|app|common)/style/"]

":recycle: refactor":
  - head-branch: ["^(fe|be|app|common)/refactor/"]

"⚙️ chore":
  - head-branch: ["^(fe|be|app|common)/chore/"]
