import { Platform, StyleSheet } from 'react-native';
import { tokens as t } from '../../ui/tokens';
import { noticeLayout as n } from '../notices/layout';

export const assignmentStyles = StyleSheet.create({
  page: { flex: 1, backgroundColor: t.color.background },
  content: {
    width: '100%',
    maxWidth: t.size.content,
    alignSelf: 'center',
    paddingHorizontal: t.space.gutter,
    flex: 1,
  },
  header: { width: '100%', maxWidth: t.size.content, alignSelf: 'center' },
  more: {
    position: 'absolute',
    right: t.space.gutter,
    bottom: t.space.sm,
    width: t.space.section,
    height: t.size.touch,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: { marginTop: n.titleTop, marginBottom: t.space.xs },
  tabs: { flexDirection: 'row', marginTop: t.space.md },
  tab: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: n.tabPadding,
    borderBottomWidth: t.size.line,
    borderBottomColor: t.color.border,
  },
  selected: { borderBottomColor: t.color.brand },
  group: { gap: t.space.sm },
  row: { flexDirection: 'row', alignItems: 'center', gap: t.space.xs },
  between: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  green: { color: t.color.brand },
  section: { gap: t.space.sm },
  summary: {
    paddingTop: n.summaryTop,
    paddingBottom: t.space.xl,
    gap: t.space.xxl,
  },
  count: { flexDirection: 'row', alignItems: 'baseline', gap: t.space.xs },
  number: {
    fontSize: n.countFontSize,
    lineHeight: n.countLineHeight,
    color: t.color.brand,
  },
  track: {
    height: t.space.sm,
    borderRadius: t.radius.pill,
    backgroundColor: t.color.mutedBackground,
    overflow: 'hidden',
  },
  progress: {
    height: t.space.sm,
    backgroundColor: t.color.brand,
    borderRadius: t.radius.pill,
  },
  person: {
    minHeight: n.recipientHeight,
    padding: t.space.gutter - t.size.line,
    gap: t.space.md,
    borderWidth: t.size.line,
    borderColor: t.color.border,
    borderRadius: t.radius.md,
    flexDirection: 'row',
    alignItems: 'center',
  },
  emptySubmission: {
    minHeight: 80,
    alignItems: 'center',
    justifyContent: 'center',
  },
  block: {
    backgroundColor: t.color.subtle,
    borderRadius: t.radius.md,
    padding: t.space.gutter,
    gap: t.space.xs,
  },
  detail: {
    paddingTop: t.space.gutter,
    paddingBottom: t.space.section,
    gap: t.space.md,
  },
  selfSection: { marginTop: t.space.xl, gap: t.space.sm },
  bodyField: {
    height: n.bodyFieldHeight,
    textAlignVertical: 'top',
    ...Platform.select({
      web: { wordBreak: 'keep-all', overflowWrap: 'anywhere' },
      default: {},
    }),
  },
  add: {
    minHeight: t.size.control,
    backgroundColor: t.color.subtle,
    borderRadius: t.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: t.space.xs,
  },
  file: {
    minHeight: t.size.control,
    borderWidth: t.size.line,
    borderColor: t.color.border,
    borderRadius: t.radius.md,
    padding: t.space.controlVertical,
    flexDirection: 'row',
    alignItems: 'center',
    gap: t.space.sm,
  },
  menu: {
    position: 'absolute',
    right: t.space.gutter,
    top: n.menuTop,
    width: n.menuWidth,
    backgroundColor: t.color.background,
    borderWidth: t.size.line,
    borderColor: t.color.border,
    borderRadius: t.radius.md,
    zIndex: 2,
  },
  menuItem: { paddingVertical: n.menuItemPadding, alignItems: 'center' },
});
