DROP TABLE IF EXISTS auth_sessions;
DROP TABLE IF EXISTS social_accounts;
DROP TABLE IF EXISTS notification;
DROP TABLE IF EXISTS notice_reminders;
DROP TABLE IF EXISTS notice_recipients;
DROP TABLE IF EXISTS notices;
DROP TABLE IF EXISTS assignment_reminders;
DROP TABLE IF EXISTS assignment_submissions;
DROP TABLE IF EXISTS assignment_recipients;
DROP TABLE IF EXISTS assignments;
DROP TABLE IF EXISTS study_members;
DROP TABLE IF EXISTS studies;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    profile_image_url VARCHAR(2048),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS social_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(32) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_social_accounts_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_social_accounts_provider_provider_user_id UNIQUE (provider, provider_user_id),
    CONSTRAINT ck_social_accounts_provider CHECK (provider IN ('GOOGLE', 'KAKAO', 'APPLE'))
);

CREATE TABLE IF NOT EXISTS auth_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    refresh_token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_auth_sessions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_auth_sessions_user_id UNIQUE (user_id),
    CONSTRAINT uk_auth_sessions_refresh_token_hash UNIQUE (refresh_token_hash)
);

CREATE TABLE IF NOT EXISTS studies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS study_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    profile_image_url VARCHAR(2048),
    role VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_study_members_study FOREIGN KEY (study_id) REFERENCES studies (id),
    CONSTRAINT fk_study_members_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_study_members_study_user UNIQUE (study_id, user_id),
    CONSTRAINT ck_study_members_role CHECK (role IN ('LEADER', 'MEMBER'))
);

CREATE TABLE IF NOT EXISTS assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    submission_method VARCHAR(255),
    close_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_assignments_study FOREIGN KEY (study_id) REFERENCES studies (id)
);

CREATE TABLE IF NOT EXISTS assignment_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    assignment_id BIGINT NOT NULL,
    content TEXT,
    link TEXT,
    submitted BOOLEAN NOT NULL,
    submitted_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_assignment_submissions_member FOREIGN KEY (member_id) REFERENCES study_members (id),
    CONSTRAINT fk_assignment_submissions_assignment FOREIGN KEY (assignment_id) REFERENCES assignments (id),
    CONSTRAINT uk_assignment_submissions_assignment_member UNIQUE (assignment_id, member_id)
);

CREATE TABLE IF NOT EXISTS assignment_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT NOT NULL,
    remind_at TIMESTAMP(6) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_assignment_reminders_assignment FOREIGN KEY (assignment_id) REFERENCES assignments (id),
    CONSTRAINT ck_assignment_reminders_status CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
);

CREATE TABLE IF NOT EXISTS notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_notices_study FOREIGN KEY (study_id) REFERENCES studies (id)
);

CREATE TABLE IF NOT EXISTS notice_recipients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    notice_id BIGINT NOT NULL,
    read_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_notice_recipients_member FOREIGN KEY (member_id) REFERENCES study_members (id),
    CONSTRAINT fk_notice_recipients_notice FOREIGN KEY (notice_id) REFERENCES notices (id),
    CONSTRAINT uk_notice_recipients_notice_member UNIQUE (notice_id, member_id)
);

CREATE TABLE IF NOT EXISTS notice_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id BIGINT NOT NULL,
    remind_at TIMESTAMP(6) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_notice_reminders_notice FOREIGN KEY (notice_id) REFERENCES notices (id),
    CONSTRAINT ck_notice_reminders_status CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
);

CREATE TABLE IF NOT EXISTS notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    resource_id BIGINT NOT NULL,
    resource_type VARCHAR(255) NOT NULL,
    is_read BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_notification_study FOREIGN KEY (study_id) REFERENCES studies (id),
    CONSTRAINT fk_notification_recipient FOREIGN KEY (recipient_id) REFERENCES study_members (id),
    CONSTRAINT ck_notification_type CHECK (type IN ('REMIND')),
    CONSTRAINT ck_notification_resource_type CHECK (resource_type IN ('NOTICE', 'ASSIGNMENT'))
);

DELETE FROM notification;
DELETE FROM notice_reminders;
DELETE FROM notice_recipients;
DELETE FROM notices;
DELETE FROM assignment_reminders;
DELETE FROM assignment_submissions;
DELETE FROM assignments;
DELETE FROM study_members;
DELETE FROM studies;
DELETE FROM auth_sessions;
DELETE FROM social_accounts;
DELETE FROM users;

ALTER TABLE notification ALTER COLUMN id RESTART WITH 1;
ALTER TABLE notice_reminders ALTER COLUMN id RESTART WITH 1;
ALTER TABLE notice_recipients ALTER COLUMN id RESTART WITH 1;
ALTER TABLE notices ALTER COLUMN id RESTART WITH 1;
ALTER TABLE assignment_reminders ALTER COLUMN id RESTART WITH 1;
ALTER TABLE assignment_submissions ALTER COLUMN id RESTART WITH 1;
ALTER TABLE assignments ALTER COLUMN id RESTART WITH 1;
ALTER TABLE study_members ALTER COLUMN id RESTART WITH 1;
ALTER TABLE studies ALTER COLUMN id RESTART WITH 1;
ALTER TABLE auth_sessions ALTER COLUMN id RESTART WITH 1;
ALTER TABLE social_accounts ALTER COLUMN id RESTART WITH 1;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;

INSERT INTO users (name, profile_image_url, created_at, updated_at)
VALUES ('바니', 'https://example.com/profiles/bunny.png', TIMESTAMP '2026-07-01 09:00:00', TIMESTAMP '2026-07-01 09:00:00'),
       ('총총', 'https://example.com/profiles/chongchong.png', TIMESTAMP '2026-07-01 09:05:00', TIMESTAMP '2026-07-01 09:05:00'),
       ('코코', NULL, TIMESTAMP '2026-07-01 09:10:00', TIMESTAMP '2026-07-01 09:10:00'),
       ('모카', 'https://example.com/profiles/mocha.png', TIMESTAMP '2026-07-02 10:00:00', TIMESTAMP '2026-07-02 10:00:00'),
       ('두부', NULL, TIMESTAMP '2026-07-02 10:05:00', TIMESTAMP '2026-07-02 10:05:00'),
       ('라떼', 'https://example.com/profiles/latte.png', TIMESTAMP '2026-07-03 11:00:00', TIMESTAMP '2026-07-03 11:00:00'),
       ('보리', 'https://example.com/profiles/bori.png', TIMESTAMP '2026-07-03 11:05:00', TIMESTAMP '2026-07-03 11:05:00'),
       ('루루', NULL, TIMESTAMP '2026-07-04 12:00:00', TIMESTAMP '2026-07-04 12:00:00');

INSERT INTO studies (name, description, created_at, updated_at)
VALUES ('자바 딥다이브', '매주 월요일 객체지향과 Java 핵심 원리를 학습합니다.', TIMESTAMP '2026-07-05 10:00:00', TIMESTAMP '2026-07-05 10:00:00'),
       ('스프링 실전 프로젝트', 'Spring Boot로 실전 서비스를 함께 개발합니다.', TIMESTAMP '2026-07-06 11:00:00', TIMESTAMP '2026-07-06 11:00:00'),
       ('알고리즘 챌린지', '주 3회 알고리즘 문제를 풀고 풀이를 공유합니다.', TIMESTAMP '2026-07-07 12:00:00', TIMESTAMP '2026-07-07 12:00:00'),
       ('루루의 1인 스터디', '수신자가 없는 공지와 1인 스터디 경계값을 테스트합니다.', TIMESTAMP '2026-07-08 13:00:00', TIMESTAMP '2026-07-08 13:00:00');

INSERT INTO study_members (study_id, user_id, name, profile_image_url, role, created_at, updated_at)
VALUES (1, 1, '바니', 'https://example.com/profiles/bunny.png', 'LEADER', TIMESTAMP '2026-07-05 10:00:00', TIMESTAMP '2026-07-05 10:00:00'),
       (1, 2, '총총', 'https://example.com/profiles/chongchong.png', 'MEMBER', TIMESTAMP '2026-07-05 10:10:00', TIMESTAMP '2026-07-05 10:10:00'),
       (1, 3, '코코', NULL, 'MEMBER', TIMESTAMP '2026-07-05 10:20:00', TIMESTAMP '2026-07-05 10:20:00'),
       (1, 4, '모카', 'https://example.com/profiles/mocha.png', 'MEMBER', TIMESTAMP '2026-07-05 10:30:00', TIMESTAMP '2026-07-05 10:30:00'),
       (1, 5, '두부', NULL, 'MEMBER', TIMESTAMP '2026-07-05 10:40:00', TIMESTAMP '2026-07-05 10:40:00'),
       (2, 2, '총총', 'https://example.com/profiles/chongchong.png', 'LEADER', TIMESTAMP '2026-07-06 11:00:00', TIMESTAMP '2026-07-06 11:00:00'),
       (2, 1, '바니', 'https://example.com/profiles/bunny.png', 'MEMBER', TIMESTAMP '2026-07-06 11:10:00', TIMESTAMP '2026-07-06 11:10:00'),
       (2, 3, '코코', NULL, 'MEMBER', TIMESTAMP '2026-07-06 11:20:00', TIMESTAMP '2026-07-06 11:20:00'),
       (2, 6, '라떼', 'https://example.com/profiles/latte.png', 'MEMBER', TIMESTAMP '2026-07-06 11:30:00', TIMESTAMP '2026-07-06 11:30:00'),
       (2, 7, '보리', 'https://example.com/profiles/bori.png', 'MEMBER', TIMESTAMP '2026-07-06 11:40:00', TIMESTAMP '2026-07-06 11:40:00'),
       (3, 3, '코코', NULL, 'LEADER', TIMESTAMP '2026-07-07 12:00:00', TIMESTAMP '2026-07-07 12:00:00'),
       (3, 4, '모카', 'https://example.com/profiles/mocha.png', 'MEMBER', TIMESTAMP '2026-07-07 12:10:00', TIMESTAMP '2026-07-07 12:10:00'),
       (3, 5, '두부', NULL, 'MEMBER', TIMESTAMP '2026-07-07 12:20:00', TIMESTAMP '2026-07-07 12:20:00'),
       (3, 8, '루루', NULL, 'MEMBER', TIMESTAMP '2026-07-07 12:30:00', TIMESTAMP '2026-07-07 12:30:00'),
       (4, 8, '루루', NULL, 'LEADER', TIMESTAMP '2026-07-08 13:00:00', TIMESTAMP '2026-07-08 13:00:00');

INSERT INTO assignments (study_id, title, content, submission_method, close_at, created_at, updated_at)
VALUES (1, '1주차 JVM 구조', 'JVM 메모리 구조와 클래스 로딩 과정을 정리합니다.', 'GitHub PR', TIMESTAMP '2026-08-03 23:59:59', TIMESTAMP '2026-07-20 09:00:00', TIMESTAMP '2026-07-20 09:00:00'),
       (1, '2주차 객체지향 설계', '책임과 협력 중심으로 주문 도메인을 설계합니다.', 'GitHub PR', TIMESTAMP '2026-08-10 23:59:59', TIMESTAMP '2026-07-27 09:00:00', TIMESTAMP '2026-07-27 09:00:00'),
       (1, '3주차 컬렉션', '컬렉션 프레임워크를 활용해 통계 기능을 구현합니다.', 'GitHub PR', TIMESTAMP '2026-08-17 23:59:59', TIMESTAMP '2026-08-03 09:00:00', TIMESTAMP '2026-08-03 09:00:00'),
       (1, '4주차 동시성', '동시성 문제를 재현하고 해결 과정을 기록합니다.', 'GitHub PR', TIMESTAMP '2026-08-24 23:59:59', TIMESTAMP '2026-08-10 09:00:00', TIMESTAMP '2026-08-10 09:00:00'),
       (2, '요구사항 분석', '사용자 스토리와 API 초안을 작성합니다.', 'Notion 링크', TIMESTAMP '2026-08-05 23:59:59', TIMESTAMP '2026-07-22 10:00:00', TIMESTAMP '2026-07-22 10:00:00'),
       (2, 'JPA 연관관계', '핵심 엔티티의 연관관계와 조회 전략을 설계합니다.', 'GitHub PR', TIMESTAMP '2026-08-12 23:59:59', TIMESTAMP '2026-07-29 10:00:00', TIMESTAMP '2026-07-29 10:00:00'),
       (2, '인증·인가 구현', 'JWT 인증과 스터디별 인가 정책을 구현합니다.', 'GitHub PR', TIMESTAMP '2026-08-19 23:59:59', TIMESTAMP '2026-08-05 10:00:00', TIMESTAMP '2026-08-05 10:00:00'),
       (2, '배포 자동화', 'CI/CD 파이프라인을 구성하고 배포 문서를 작성합니다.', 'GitHub Repository', TIMESTAMP '2026-08-26 23:59:59', TIMESTAMP '2026-08-12 10:00:00', TIMESTAMP '2026-08-12 10:00:00'),
       (3, '그리디 10문제', '필수 그리디 문제 10개를 풀고 복잡도를 기록합니다.', '문제 풀이 링크', TIMESTAMP '2026-08-07 23:59:59', TIMESTAMP '2026-07-24 11:00:00', TIMESTAMP '2026-07-24 11:00:00'),
       (3, '그래프 탐색 10문제', 'BFS와 DFS 유형별 풀이를 비교합니다.', '문제 풀이 링크', TIMESTAMP '2026-08-14 23:59:59', TIMESTAMP '2026-07-31 11:00:00', TIMESTAMP '2026-07-31 11:00:00'),
       (3, '동적 계획법 10문제', '점화식 도출 과정을 포함해 풀이합니다.', '문제 풀이 링크', TIMESTAMP '2026-08-21 23:59:59', TIMESTAMP '2026-08-07 11:00:00', TIMESTAMP '2026-08-07 11:00:00'),
       (4, '주간 회고', '한 주 동안 학습한 내용을 짧게 회고합니다.', NULL, TIMESTAMP '2026-08-23 23:59:59', TIMESTAMP '2026-08-16 12:00:00', TIMESTAMP '2026-08-16 12:00:00');

INSERT INTO assignment_submissions (
    member_id,
    assignment_id,
    content,
    link,
    submitted,
    submitted_at,
    created_at,
    updated_at
)
SELECT member.id,
       assignment.id,
       CASE
           WHEN MOD(member.id + assignment.id, 3) = 0 THEN '과제를 제출했습니다.'
           ELSE NULL
       END,
       CASE
           WHEN MOD(member.id + assignment.id, 3) = 0
               THEN CONCAT('https://github.com/chongchong/study-', assignment.study_id,
                           '/assignments/', assignment.id, '/members/', member.id)
           ELSE NULL
       END,
       CASE
           WHEN MOD(member.id + assignment.id, 3) = 0 THEN TRUE
           ELSE FALSE
       END,
       CASE
           WHEN MOD(member.id + assignment.id, 3) = 0 THEN assignment.created_at
           ELSE NULL
       END,
       assignment.created_at,
       assignment.created_at
FROM assignments assignment
JOIN study_members member
  ON member.study_id = assignment.study_id
 AND member.role = 'MEMBER';

INSERT INTO assignment_reminders (assignment_id, remind_at, status, created_at, updated_at)
VALUES (1, TIMESTAMP '2026-08-03 20:00:00', 'SENT', TIMESTAMP '2026-07-20 09:00:00', TIMESTAMP '2026-08-03 20:00:00'),
       (3, TIMESTAMP '2026-08-17 20:00:00', 'FAILED', TIMESTAMP '2026-08-03 09:00:00', TIMESTAMP '2026-08-17 20:00:00'),
       (4, TIMESTAMP '2026-08-24 20:00:00', 'SENT', TIMESTAMP '2026-08-10 09:00:00', TIMESTAMP '2026-08-24 20:00:00'),
       (7, TIMESTAMP '2026-08-19 20:00:00', 'SENT', TIMESTAMP '2026-08-05 10:00:00', TIMESTAMP '2026-08-19 20:00:00'),
       (8, TIMESTAMP '2026-08-26 18:00:00', 'PENDING', TIMESTAMP '2026-08-12 10:00:00', TIMESTAMP '2026-08-12 10:00:00'),
       (11, TIMESTAMP '2026-08-21 20:00:00', 'SENT', TIMESTAMP '2026-08-07 11:00:00', TIMESTAMP '2026-08-21 20:00:00');

INSERT INTO notices (study_id, title, content, created_at, updated_at)
VALUES (1, '첫 모임 안내', '첫 모임은 월요일 오후 8시, 온라인으로 진행합니다.', TIMESTAMP '2026-08-01 09:00:00', TIMESTAMP '2026-08-01 09:00:00'),
       (1, '개발 환경 설정', 'JDK 25와 IntelliJ 프로젝트 설정을 확인해 주세요.', TIMESTAMP '2026-08-02 09:00:00', TIMESTAMP '2026-08-02 09:00:00'),
       (1, '1주차 발표 순서', '바니, 총총, 코코, 모카, 두부 순서로 발표합니다.', TIMESTAMP '2026-08-03 09:00:00', TIMESTAMP '2026-08-03 09:00:00'),
       (1, 'JVM 자료 공유', 'JVM 구조 참고 자료를 스터디 문서에 추가했습니다.', TIMESTAMP '2026-08-04 09:00:00', TIMESTAMP '2026-08-04 09:00:00'),
       (1, '코드 리뷰 규칙', 'PR은 최소 한 명의 승인을 받은 뒤 병합합니다.', TIMESTAMP '2026-08-05 09:00:00', TIMESTAMP '2026-08-05 09:00:00'),
       (1, '2주차 모임 장소', '2주차 모임은 강남 스터디룸 B에서 진행합니다.', TIMESTAMP '2026-08-06 09:00:00', TIMESTAMP '2026-08-06 09:00:00'),
       (1, '과제 제출 형식', '저장소 링크와 회고를 함께 제출해 주세요.', TIMESTAMP '2026-08-07 09:00:00', TIMESTAMP '2026-08-07 09:00:00'),
       (1, '휴강 안내', '광복절 주간은 쉬고 다음 주에 다시 진행합니다.', TIMESTAMP '2026-08-08 09:00:00', TIMESTAMP '2026-08-08 09:00:00'),
       (1, '질문 채널 안내', '질문은 슬랙 java-help 채널에 남겨 주세요.', TIMESTAMP '2026-08-09 09:00:00', TIMESTAMP '2026-08-09 09:00:00'),
       (1, '중간 회고', '지금까지 좋았던 점과 개선할 점을 작성해 주세요.', TIMESTAMP '2026-08-10 09:00:00', TIMESTAMP '2026-08-10 09:00:00'),
       (1, '3주차 준비사항', '컬렉션 프레임워크 실습 코드를 미리 받아 주세요.', TIMESTAMP '2026-08-11 09:00:00', TIMESTAMP '2026-08-11 09:00:00'),
       (1, '페어 프로그래밍 조 편성', '총총-코코, 모카-두부 조로 진행합니다.', TIMESTAMP '2026-08-12 09:00:00', TIMESTAMP '2026-08-12 09:00:00'),
       (1, '라이브 코딩 안내', '다음 모임에는 컬렉션 리팩터링 라이브 코딩이 있습니다.', TIMESTAMP '2026-08-13 09:00:00', TIMESTAMP '2026-08-13 09:00:00'),
       (1, '동시성 사전 자료', '스레드와 락 관련 사전 자료를 읽어 와 주세요.', TIMESTAMP '2026-08-14 09:00:00', TIMESTAMP '2026-08-14 09:00:00'),
       (1, '다음 달 일정 조사', '가능한 요일을 설문에 체크해 주세요.', TIMESTAMP '2026-08-15 09:00:00', TIMESTAMP '2026-08-15 09:00:00'),
       (2, '프로젝트 킥오프', '프로젝트 목표와 1차 마일스톤을 공유합니다.', TIMESTAMP '2026-08-01 10:00:00', TIMESTAMP '2026-08-01 10:00:00'),
       (2, '브랜치 전략', '기능 브랜치는 feat 이슈번호 형식으로 생성합니다.', TIMESTAMP '2026-08-03 10:00:00', TIMESTAMP '2026-08-03 10:00:00'),
       (2, 'API 명세 리뷰', '수요일 오후 9시에 API 명세를 함께 리뷰합니다.', TIMESTAMP '2026-08-05 10:00:00', TIMESTAMP '2026-08-05 10:00:00'),
       (2, 'DB 모델링 회의', 'ERD 초안을 기준으로 연관관계를 확정합니다.', TIMESTAMP '2026-08-07 10:00:00', TIMESTAMP '2026-08-07 10:00:00'),
       (2, '1차 스프린트 회고', 'Keep, Problem, Try 형식으로 회고를 준비해 주세요.', TIMESTAMP '2026-08-09 10:00:00', TIMESTAMP '2026-08-09 10:00:00'),
       (2, '인증 API 테스트', 'Postman 환경에 테스트용 Access Token을 등록해 주세요.', TIMESTAMP '2026-08-11 10:00:00', TIMESTAMP '2026-08-11 10:00:00'),
       (2, '코드 프리즈', '금요일 오후 6시 이후에는 버그 수정만 반영합니다.', TIMESTAMP '2026-08-13 10:00:00', TIMESTAMP '2026-08-13 10:00:00'),
       (2, '데모 일정', '최종 데모는 8월 28일 오후 8시에 진행합니다.', TIMESTAMP '2026-08-15 10:00:00', TIMESTAMP '2026-08-15 10:00:00'),
       (3, '이번 주 문제 목록', '그리디와 정렬 문제 5개를 풀어 주세요.', TIMESTAMP '2026-08-02 11:00:00', TIMESTAMP '2026-08-02 11:00:00'),
       (3, '풀이 공유 규칙', '시간 복잡도와 핵심 아이디어를 반드시 적어 주세요.', TIMESTAMP '2026-08-05 11:00:00', TIMESTAMP '2026-08-05 11:00:00'),
       (3, '온라인 모각코', '목요일 오후 10시부터 한 시간 동안 진행합니다.', TIMESTAMP '2026-08-08 11:00:00', TIMESTAMP '2026-08-08 11:00:00'),
       (3, 'BFS 특강', '다음 모임에서 격자 탐색 문제를 함께 풉니다.', TIMESTAMP '2026-08-11 11:00:00', TIMESTAMP '2026-08-11 11:00:00'),
       (3, '문제 난이도 설문', '다음 주 문제 난이도를 설문으로 선택해 주세요.', TIMESTAMP '2026-08-14 11:00:00', TIMESTAMP '2026-08-14 11:00:00'),
       (3, '주간 랭킹 안내', '주간 풀이 수는 재미를 위한 지표이며 평가에 사용하지 않습니다.', TIMESTAMP '2026-08-17 11:00:00', TIMESTAMP '2026-08-17 11:00:00'),
       (4, '첫 번째 개인 공지', '수신자가 없는 공지도 정상적으로 조회되는지 확인합니다.', TIMESTAMP '2026-08-18 12:00:00', TIMESTAMP '2026-08-18 12:00:00');

INSERT INTO notice_recipients (member_id, notice_id, read_at, created_at, updated_at)
SELECT member.id,
       notice.id,
       CASE
           WHEN MOD(member.id + notice.id, 3) = 0 THEN notice.created_at
           ELSE NULL
       END,
       notice.created_at,
       notice.created_at
FROM notices notice
JOIN study_members member
  ON member.study_id = notice.study_id
 AND member.role = 'MEMBER';

INSERT INTO notice_reminders (notice_id, remind_at, status, created_at, updated_at)
VALUES (1, TIMESTAMP '2026-08-01 19:00:00', 'SENT', TIMESTAMP '2026-08-01 09:00:00', TIMESTAMP '2026-08-01 19:00:00'),
       (3, TIMESTAMP '2026-08-03 19:00:00', 'SENT', TIMESTAMP '2026-08-03 09:00:00', TIMESTAMP '2026-08-03 19:00:00'),
       (5, TIMESTAMP '2026-08-05 18:00:00', 'FAILED', TIMESTAMP '2026-08-05 09:00:00', TIMESTAMP '2026-08-05 18:00:00'),
       (6, TIMESTAMP '2026-08-06 19:00:00', 'SENT', TIMESTAMP '2026-08-06 09:00:00', TIMESTAMP '2026-08-06 19:00:00'),
       (8, TIMESTAMP '2026-08-08 18:00:00', 'SENT', TIMESTAMP '2026-08-08 09:00:00', TIMESTAMP '2026-08-08 18:00:00'),
       (10, TIMESTAMP '2026-08-10 20:00:00', 'SENT', TIMESTAMP '2026-08-10 09:00:00', TIMESTAMP '2026-08-10 20:00:00'),
       (12, TIMESTAMP '2026-08-12 19:00:00', 'SENT', TIMESTAMP '2026-08-12 09:00:00', TIMESTAMP '2026-08-12 19:00:00'),
       (14, TIMESTAMP '2026-08-21 20:00:00', 'PENDING', TIMESTAMP '2026-08-14 09:00:00', TIMESTAMP '2026-08-14 09:00:00'),
       (15, TIMESTAMP '2026-08-22 20:00:00', 'PENDING', TIMESTAMP '2026-08-15 09:00:00', TIMESTAMP '2026-08-15 09:00:00'),
       (16, TIMESTAMP '2026-08-01 20:00:00', 'SENT', TIMESTAMP '2026-08-01 10:00:00', TIMESTAMP '2026-08-01 20:00:00'),
       (18, TIMESTAMP '2026-08-05 20:00:00', 'SENT', TIMESTAMP '2026-08-05 10:00:00', TIMESTAMP '2026-08-05 20:00:00'),
       (20, TIMESTAMP '2026-08-09 20:00:00', 'FAILED', TIMESTAMP '2026-08-09 10:00:00', TIMESTAMP '2026-08-09 20:00:00'),
       (21, TIMESTAMP '2026-08-11 20:00:00', 'SENT', TIMESTAMP '2026-08-11 10:00:00', TIMESTAMP '2026-08-11 20:00:00'),
       (22, TIMESTAMP '2026-08-20 18:00:00', 'PENDING', TIMESTAMP '2026-08-13 10:00:00', TIMESTAMP '2026-08-13 10:00:00'),
       (23, TIMESTAMP '2026-08-27 18:00:00', 'PENDING', TIMESTAMP '2026-08-15 10:00:00', TIMESTAMP '2026-08-15 10:00:00'),
       (24, TIMESTAMP '2026-08-02 21:00:00', 'SENT', TIMESTAMP '2026-08-02 11:00:00', TIMESTAMP '2026-08-02 21:00:00'),
       (26, TIMESTAMP '2026-08-08 21:00:00', 'SENT', TIMESTAMP '2026-08-08 11:00:00', TIMESTAMP '2026-08-08 21:00:00'),
       (28, TIMESTAMP '2026-08-21 21:00:00', 'PENDING', TIMESTAMP '2026-08-14 11:00:00', TIMESTAMP '2026-08-14 11:00:00'),
       (29, TIMESTAMP '2026-08-24 21:00:00', 'PENDING', TIMESTAMP '2026-08-17 11:00:00', TIMESTAMP '2026-08-17 11:00:00'),
       (30, TIMESTAMP '2026-08-25 12:00:00', 'PENDING', TIMESTAMP '2026-08-18 12:00:00', TIMESTAMP '2026-08-18 12:00:00');
