import {
  chongchongV2Typography as typographyVariables,
  chongchongV2 as v,
} from './figmaVariables';

const f = typographyVariables.font;
export const tokens = {
  color: {
    background: v.color.background.default,
    subtle: v.color.background.subtle,
    mutedBackground: v.color.background.muted,
    brand: v.color.brand.primary,
    brandSubtle: v.color.brand.subtle,
    text: v.color.text.primary,
    secondary: v.color.text.secondary,
    tertiary: v.color.text.tertiary,
    border: v.color.border.default,
    disabled: v.color.text.placeholder,
    disabledText: v.color.text.disabled,
    danger: v.color.status.error,
    onBrand: v.color.background.default,
    placeholder: v.color.text.placeholder,
    overlay: v.color.overlay.scrim,
  },
  space: {
    xs: v.spacing[4],
    sm: 8,
    md: v.spacing[12],
    lg: v.spacing[16],
    gutter: 20,
    xl: 24,
    xxl: 32,
    section: 40,
    badgeVertical: 5,
    badgeHorizontal: 10,
    controlVertical: 14,
  },
  radius: { sm: 8, md: 12, lg: 16, dialog: 20, pill: 999 },
  size: {
    touch: 48,
    control: 52,
    dialog: 310,
    icon: 24,
    tabIcon: 22,
    tabBar: 64,
    tabHorizontalInset: 19,
    header: 64,
    headerPadding: 18,
    line: 1,
    content: 600,
    cardMinHeight: 148,
    emptyIllustration: 150,
    toastIcon: 16,
  },
  pressedOpacity: 0.7,
  font: { regular: f.family.pretendard, strong: 'PretendardSemiBold' },
  typography: {
    title: {
      fontSize: f.size[24],
      lineHeight: f['line-height'][34],
      letterSpacing: -0.6,
    },
    subtitle: {
      fontSize: f.size[18],
      lineHeight: f['line-height'][28],
      letterSpacing: -0.45,
    },
    large: {
      fontSize: f.size[16],
      lineHeight: f['line-height'][24],
      letterSpacing: -0.4,
    },
    body: {
      fontSize: f.size[14],
      lineHeight: f['line-height'][20],
      letterSpacing: -0.35,
    },
    small: {
      fontSize: f.size[13],
      lineHeight: f['line-height'][18],
      letterSpacing: -0.325,
    },
    caption: {
      fontSize: f.size[12],
      lineHeight: f['line-height'][18],
      letterSpacing: -0.3,
    },
    compact: {
      fontSize: f.size[12],
      lineHeight: f['line-height'][16],
      letterSpacing: -0.3,
    },
  },
} as const;
