-- Replace app push-token registrations with browser Web Push subscriptions.

-- App push tokens cannot be converted into Web Push subscriptions. Abort before changing
-- the schema when an old delivery row would otherwise lose its delivery target.
ALTER TABLE notification_deliveries
    ADD CONSTRAINT ck_notification_deliveries_must_be_empty CHECK (FALSE);

ALTER TABLE notification_deliveries
    DROP CONSTRAINT ck_notification_deliveries_must_be_empty;

CREATE TABLE web_push_subscriptions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at       TIMESTAMP(6) WITHOUT TIME ZONE,
    endpoint         TEXT         NOT NULL,
    p256dh           TEXT         NOT NULL,
    auth             TEXT         NOT NULL,
    is_active        BOOLEAN      NOT NULL,
    last_success_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    last_failure_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    last_error       TEXT,
    user_id          BIGINT       NOT NULL,
    CONSTRAINT uk_web_push_subscriptions_endpoint UNIQUE (endpoint),
    CONSTRAINT fk_web_push_subscriptions_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_web_push_subscriptions_user_active
    ON web_push_subscriptions (user_id, is_active);

ALTER TABLE notification_deliveries
    DROP CONSTRAINT IF EXISTS uk_notification_delivery_notification_push_token;

ALTER TABLE notification_deliveries
    DROP CONSTRAINT IF EXISTS fk_notification_delivery_push_token;

ALTER TABLE notification_deliveries
    RENAME COLUMN push_token_id TO web_push_subscription_id;

ALTER TABLE notification_deliveries
    ADD CONSTRAINT uk_notification_delivery_notification_web_push_subscription
        UNIQUE (notification_id, web_push_subscription_id);

ALTER TABLE notification_deliveries
    ADD CONSTRAINT fk_notification_delivery_web_push_subscription
        FOREIGN KEY (web_push_subscription_id)
            REFERENCES web_push_subscriptions (id) ON DELETE CASCADE;

-- Legacy app tokens have no endpoint/key mapping and are intentionally not migrated.
DROP TABLE push_tokens;
