-- Baseline schema captured before Flyway adoption, formatted for readability.

CREATE TABLE users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at        TIMESTAMP(6) WITHOUT TIME ZONE,
    name              VARCHAR(255) NOT NULL,
    profile_image_url VARCHAR(2048)
);

CREATE TABLE studies
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    description VARCHAR(255),
    name        VARCHAR(255) NOT NULL
);

CREATE TABLE study_members
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at        TIMESTAMP(6) WITHOUT TIME ZONE,
    name              VARCHAR(255) NOT NULL,
    profile_image_url VARCHAR(2048),
    role              VARCHAR(255) NOT NULL,
    study_id          BIGINT       NOT NULL,
    user_id           BIGINT       NOT NULL,
    CONSTRAINT study_members_role_check CHECK (role IN ('LEADER', 'MEMBER')),
    CONSTRAINT uk_study_members_study_user UNIQUE (study_id, user_id),
    CONSTRAINT fkb8cp6e23p040p7ml6sswen5cs FOREIGN KEY (study_id) REFERENCES studies (id),
    CONSTRAINT fkdt5hp8mbe53a5sdcecsf7wpyg FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE assignments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at        TIMESTAMP(6) WITHOUT TIME ZONE,
    close_at          TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    content           TEXT                           NOT NULL,
    submission_method VARCHAR(255),
    title             VARCHAR(255)                   NOT NULL,
    study_id          BIGINT                         NOT NULL,
    CONSTRAINT fkqe029wvx6pjp0q8tlypilk0c9 FOREIGN KEY (study_id) REFERENCES studies (id)
);

CREATE TABLE assignment_reminders
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    remind_at     TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    status        VARCHAR(255)                   NOT NULL,
    assignment_id BIGINT                         NOT NULL,
    CONSTRAINT assignment_reminders_status_check CHECK (status IN ('PENDING', 'SENT', 'FAILED')),
    CONSTRAINT fk23if7m1gm235fcgs3hleq5do2 FOREIGN KEY (assignment_id) REFERENCES assignments (id)
);

CREATE TABLE assignment_submissions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    content       TEXT,
    link          TEXT,
    submitted     BOOLEAN NOT NULL,
    submitted_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    assignment_id BIGINT  NOT NULL,
    member_id     BIGINT  NOT NULL,
    CONSTRAINT uk_assignment_submissions_assignment_member UNIQUE (assignment_id, member_id),
    CONSTRAINT fkm7i7ubgh7y2n6mvg8muw62oax FOREIGN KEY (assignment_id) REFERENCES assignments (id),
    CONSTRAINT fknsfnkdmpdvd605vnpkpt1g0md FOREIGN KEY (member_id) REFERENCES study_members (id)
);

CREATE TABLE notices
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    content    TEXT         NOT NULL,
    title      VARCHAR(255) NOT NULL,
    study_id   BIGINT       NOT NULL,
    CONSTRAINT fk403omqxfm0hkwwx6trtd12u76 FOREIGN KEY (study_id) REFERENCES studies (id)
);

CREATE TABLE notice_recipients
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    read_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    member_id  BIGINT NOT NULL,
    notice_id  BIGINT NOT NULL,
    CONSTRAINT uk_notice_recipients_notice_member UNIQUE (notice_id, member_id),
    CONSTRAINT fkpm6u1t0n3px52tld2apx6oess FOREIGN KEY (member_id) REFERENCES study_members (id),
    CONSTRAINT fky3a9r7igh6bsqigv2lkgmu6o FOREIGN KEY (notice_id) REFERENCES notices (id)
);

CREATE TABLE notice_reminders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    remind_at  TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    status     VARCHAR(255)                   NOT NULL,
    notice_id  BIGINT                         NOT NULL,
    CONSTRAINT notice_reminders_status_check CHECK (status IN ('PENDING', 'SENT', 'FAILED')),
    CONSTRAINT fko0h19ha7jyrdtym2iy97ip03n FOREIGN KEY (notice_id) REFERENCES notices (id)
);

CREATE TABLE notifications
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    is_read       BOOLEAN      NOT NULL,
    resource_id   BIGINT       NOT NULL,
    resource_type VARCHAR(255) NOT NULL,
    type          VARCHAR(255) NOT NULL,
    recipient_id  BIGINT       NOT NULL,
    study_id      BIGINT       NOT NULL,
    CONSTRAINT notifications_resource_type_check CHECK (resource_type IN ('NOTICE', 'ASSIGNMENT')),
    CONSTRAINT notifications_type_check CHECK (type = 'REMIND'),
    CONSTRAINT fk60prjsdd6ahrlv3ayvjjqdlqi FOREIGN KEY (recipient_id) REFERENCES study_members (id),
    CONSTRAINT fko5m57o40ivnn0td7m511dx42k FOREIGN KEY (study_id) REFERENCES studies (id)
);

CREATE TABLE auth_sessions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at         TIMESTAMP(6) WITHOUT TIME ZONE,
    expires_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    refresh_token_hash VARCHAR(64)                 NOT NULL,
    user_id            BIGINT                      NOT NULL,
    CONSTRAINT uk_auth_sessions_refresh_token_hash UNIQUE (refresh_token_hash),
    CONSTRAINT uk_auth_sessions_user_id UNIQUE (user_id),
    CONSTRAINT fkpu507182mdfutajr71rgk67l FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE push_tokens
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at      TIMESTAMP(6) WITHOUT TIME ZONE,
    installation_id VARCHAR(255) NOT NULL,
    is_active       BOOLEAN      NOT NULL,
    platform        VARCHAR(255) NOT NULL,
    provider        VARCHAR(255) NOT NULL,
    token           VARCHAR(255) NOT NULL,
    user_id         BIGINT       NOT NULL,
    CONSTRAINT push_tokens_platform_check CHECK (platform IN ('ANDROID', 'IOS')),
    CONSTRAINT push_tokens_provider_check CHECK (provider IN ('EXPO', 'FCM', 'APNS')),
    CONSTRAINT uk_push_tokens_user_installation_id UNIQUE (user_id, installation_id),
    CONSTRAINT fkgisqbur2nbpemhidpyqv501nd FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE social_accounts
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at       TIMESTAMP(6) WITHOUT TIME ZONE,
    provider         VARCHAR(32)  NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    user_id          BIGINT       NOT NULL,
    CONSTRAINT social_accounts_provider_check CHECK (provider IN ('GOOGLE', 'KAKAO', 'APPLE')),
    CONSTRAINT uk_social_accounts_provider_provider_user_id UNIQUE (provider, provider_user_id),
    CONSTRAINT fk6rmxxiton5yuvu7ph2hcq2xn7 FOREIGN KEY (user_id) REFERENCES users (id)
);
