-- A notification delivery tracks one push attempt target for one notification.

CREATE TABLE notification_deliveries
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    status        VARCHAR(255) NOT NULL,
    attempt_count INTEGER      NOT NULL,
    next_retry_at TIMESTAMP(6) WITHOUT TIME ZONE,
    last_error    VARCHAR(255),
    notification_id BIGINT     NOT NULL,
    push_token_id  BIGINT      NOT NULL,
    CONSTRAINT notification_deliveries_status_check
        CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'RETRY_WAIT', 'FAILED')),
    CONSTRAINT uk_notification_delivery_notification_push_token
        UNIQUE (notification_id, push_token_id),
    CONSTRAINT fk_notification_delivery_notification
        FOREIGN KEY (notification_id) REFERENCES notifications (id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_delivery_push_token
        FOREIGN KEY (push_token_id) REFERENCES push_tokens (id) ON DELETE CASCADE
);
