import { StyleSheet } from 'react-native';
import { tokens as t } from '../../ui/tokens';
export const memberStyles = StyleSheet.create({
  group: { gap: t.space.sm },
  list: { gap: t.space.sm, marginTop: t.space.sm },
  row: {
    minHeight: 68,
    paddingHorizontal: t.space.gutter,
    borderWidth: t.size.line,
    borderColor: t.color.border,
    borderRadius: t.radius.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: t.space.sm,
  },
  avatar: {
    width: 28,
    height: 28,
    borderRadius: t.radius.pill,
    backgroundColor: t.color.mutedBackground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  name: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: t.space.xs,
    flex: 1,
  },
  touch: {
    width: t.size.touch,
    height: t.size.touch,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menu: {
    position: 'absolute',
    right: t.space.md,
    top: 14,
    width: 100,
    backgroundColor: t.color.background,
    borderWidth: t.size.line,
    borderColor: t.color.border,
    borderRadius: t.radius.md,
    zIndex: 2,
  },
  menuItem: { height: 40, justifyContent: 'center', alignItems: 'center' },
  invitation: { marginTop: t.space.sm, gap: t.space.sm },
  inviteBox: {
    height: t.size.control,
    paddingLeft: t.space.md,
    borderWidth: t.size.line,
    borderColor: t.color.border,
    borderRadius: t.radius.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: t.space.sm,
  },
  card: {
    marginTop: -16,
    alignItems: 'center',
    padding: t.space.gutter,
    gap: t.space.sm,
    borderRadius: t.radius.lg,
    borderWidth: t.size.line,
    borderColor: t.color.border,
  },
  image: { width: 70, height: 70, borderRadius: t.radius.md },
  centered: { textAlign: 'center' },
  action: {
    minHeight: 68,
    justifyContent: 'center',
    borderBottomWidth: t.size.line,
    borderBottomColor: t.color.border,
  },
  danger: { color: t.color.danger },
  profileIcon: {
    alignSelf: 'center',
    marginTop: t.space.xl,
    marginBottom: t.space.sm,
  },
  form: { gap: t.space.lg },
});
