spring:
  application:
    name: chong-chong
  config:
    import: optional:file:./.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  study-invite-secret: ${STUDY_INVITE_JWT_SECRET}

frontend:
  base-url: ${FRONTEND_BASE_URL}
