spring:
  application:
    name: chong-chong
  config:
    import: optional:file:./.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  study-invite-secret: ${STUDY_INVITE_JWT_SECRET}

frontend:
  base-url: ${FRONTEND_BASE_URL}

auth:
  jwt:
    issuer: ${AUTH_JWT_ISSUER}
    audience: ${AUTH_JWT_AUDIENCE}
    secret-base64: ${AUTH_JWT_SECRET_BASE64}
    access-token-validity: ${AUTH_JWT_ACCESS_TOKEN_VALIDITY:30m}
